### ISSUE TITLE
high cpu usage of dapr sidecars after upgrading to runtime 1.3.0-rc.x

### ISSUE THREAD

**Issue by javageek79** [dapr/dapr#3468]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.3.0-rc.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

cpu usage of sidcars does not change significantly after upgrade

## Actual Behavior

After up upgrading from dapr rt 1.2.0 to 1.3.0-rc.1 in a first run followed by a second run with rc.2, we experienced an unexpected high cpu consumption of our dapr sidecars across our services.

cpu usage of java/node services after 1.3.0-rc.x upgrade
![java-service-dapr-v1 3 0](https://user-images.githubusercontent.com/3714921/126601406-a9f2d320-1492-4f2e-ba21-f59106bb3886.png)
![node-service-dapr-v1 3 0](https://user-images.githubusercontent.com/3714921/126601410-8e658113-014e-4050-ac4a-352f32723d60.png)
![image (3)](https://user-images.githubusercontent.com/3714921/126601411-d7f414e3-763c-42dc-9bd8-b13e0dee7897.png)
![image (5)](https://user-images.githubusercontent.com/3714921/126601412-3ea70abf-af36-409f-a17d-24fbf253c08a.png)

cpu usage of java/node services with 1.2.0
![java-service-dapr-v1 2 0](https://user-images.githubusercontent.com/3714921/126601401-df4cacad-7e36-49ad-b40b-85a8453a47ad.png)
![node-service-dapr-v1 2 0](https://user-images.githubusercontent.com/3714921/126601408-2297a7fc-0016-4741-b15b-b3c08a437e14.png)

we are currently running on k8s ver. 1.19.7

## Release Note

RELEASE NOTE:

**Comment by stefanJ-hub** [comment]
fyi @artursouza

**Comment by wcs1only** [comment]
Just to add some context, we have a known regression in 1.3.0-rc.1 that was rolled back in 1.3.0-rc.2. If you've upgraded to rc.2 be sure and do a rolling restart of your services to pick up the fix. We also fixed another performance regression in 1.3.0-rc.3, but it is specific to the dotnet, and python SDK's and their actor implementation.

If you've already updated to rc.2 and done a rolling restart, there may be something additional lurking that we didn't catch.

**Comment by wcs1only** [comment]
Here's how you can definitively verify that you've got the rc.2 fix fully deployed:

``` bash
# rc.1 with the known regression:
kubectl describe pod <your_pod> | grep Liveness
    Liveness:       exec [/daprd --wait --dapr-http-port 3500] delay=3s timeout=3s period=6s #success=1 #failure=3

# rc.2 with the regression fixed
kubectl describe pod  <your_pod> | grep Liveness
    Liveness:       http-get http://:3500/v1.0/healthz delay=3s timeout=3s period=6s #success=1 #failure=3
```

If you see that Liveness is using an HTTP probe as above, you've got the fix (and the CPU regression is something yet unknown)

**Comment by wcs1only** [comment]
If we can rule out the above, the next best step will be to see if we can capture a profile: https://docs.dapr.io/operations/troubleshooting/profiling-debugging/

If we can get one against 1.2.2 and one against 1.3.0-rc.3, we can compare them, and the CPU usage should stick out pretty dramatically, based on the size of the regression you've seen.

**Comment by pkedy** [comment]
Here is a handy tool to visualize the pprof data: https://github.com/remeh/diago

**Comment by javageek79** [comment]
Hi, thanks for the hints. We rolled out dapr runtime 1.3.0-rc3. We still experience a high CPU consumption of the sidecars with this version.

Some points we discovered:
-	It takes some time until the high CPU consumption happens – it does not happen directly after the update/restart
-	Our services use Pub/Sub. Some services subscribe and publish and other services only use publish. We see the high CPU consumption only for services that act as subscriber
-	We checked `kubectl describe pod  <your_pod> | grep Liveness` and we got something like `http-get http://:3500/v1.0/healthz delay=3s timeout=3s period=6s #success=1 #failure=3`

**Comment by wcs1only** [comment]
We believe that we have identified a potential root cause for the issue you have described. We'll be cutting a 1.3.0-rc.4 shortly.

**Comment by wcs1only** [comment]
Release 1.3.0-rc.4 is now available, and we believe it may address the issue you have reported. Please let us know if it solves your issue.

**Comment by javageek79** [comment]
thx for the effort and the fix. With rc.4 issues were gone.
