### ISSUE TITLE
Sidecar tries to delete reminder even though app has unregistered it

### ISSUE THREAD

**Issue by sujitdmello** [dapr/dapr#6666]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.11.1

## Expected Behavior

Java app responding to a **receiveReminder** callback, calls **super.unregisterReminder().block()** which should delete the reminder and not result in any errors. 

## Actual Behavior

The receiveReminder method calls **super.unregisterReminder().block()** and receives no errors, and the reminder finishes processing. Then the sidecar logs an error *Could not find active reminder with key*.

```log
== APP == 2023-07-14 08:13:57.039  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorImpl            : Reminder received for long retry # 1
time="2023-07-14T08:13:57.0567597-04:00" level=debug msg="Found reminder with key: CheckoutActor||1000||constantRetryReminder1. Deleting reminder" app_id=checkout-actor instance=DESKTOP-70K7KP5 scope=dapr.runtime.actor type=log ver=1.11.1
time="2023-07-14T08:13:57.1813354-04:00" level=debug msg="starting to read reminders for actor type CheckoutActor (migrate=false), with metadata id 00000000-0000-0000-0000-000000000000 and 0 partitions" app_id=checkout-actor instance=DESKTOP-70K7KP5 scope=dapr.runtime.actor type=log ver=1.11.1
time="2023-07-14T08:13:57.1976031-04:00" level=debug msg="read reminders from actors||CheckoutActor without partition" app_id=checkout-actor instance=DESKTOP-70K7KP5 scope=dapr.runtime.actor type=log ver=1.11.1
time="2023-07-14T08:13:57.2031242-04:00" level=debug msg="finished reading reminders for actor type CheckoutActor (migrate=false), with metadata id 00000000-0000-0000-0000-000000000000 and no partitions: total of 1 reminders" app_id=checkout-actor instance=DESKTOP-70K7KP5 scope=dapr.runtime.actor type=log ver=1.11.1
== APP == 2023-07-14 08:13:57.321  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorImpl            : Reminder constantRetryReminder1 unregistered.
== APP == 2023-07-14 08:13:57.322  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorImpl            : Reading actor state for actor Id 1000
== APP == 2023-07-14 08:13:57.357  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorImpl            : Processing reminder for order 1000.
time="2023-07-14T08:13:57.3706644-04:00" level=debug msg="Found Component Outbound Policy for component http-order-service: {Timeout:general Retry:shortRetry CircuitBreaker:simpleCB}" app_id=checkout-actor instance=DESKTOP-70K7KP5 scope=dapr.runtime type=log ver=1.11.1
== APP == 2023-07-14 08:13:57.480  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorLogic           : Order passed: 1000, orderResponse: OrderResponse(orderId=CID1000, status=Processed)
== APP == 2023-07-14 08:13:57.480  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorImpl            : Order 1000 has been placed.
== APP == 2023-07-14 08:13:57.480  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorImpl            : Updating actor state for order 1000.
== APP == 2023-07-14 08:13:57.549  INFO 13768 --- [nio-9002-exec-4] com.service.CheckoutActorImpl            : Order 1000 state has been updated.
time="2023-07-14T08:13:57.5530562-04:00" level=error msg="Could not find active reminder with key: CheckoutActor||1000||constantRetryReminder1" app_id=checkout-actor instance=DESKTOP-70K7KP5 scope=dapr.runtime.actor type=log ver=1.11.1
```

While this does not cause any problems with the runtime or the app, the error seems out of place and is possibly an indication that we are not doing something right in the app.

## Steps to Reproduce the Problem

A variation of the [Java resiliency sample](https://docs.dapr.io/getting-started/quickstarts/resiliency/resiliency-serviceinvo-quickstart/) was used to create a simple Actor that has a method that registers a Reminder and then responds to that Reminder. 

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
If the reminder is executed, and has no repetitions (or no repetitions left), it should be deleted automatically by Dapr. I don't think calling unregisterReminder is needed.

**Comment by artursouza** [comment]
> If the reminder is executed, and has no repetitions (or no repetitions left), it should be deleted automatically by Dapr. I don't think calling unregisterReminder is needed.

Correct.

**Comment by sujitdmello** [comment]
Yes that is how we originally had it but when load testing with many reminders, we had issues like missing reminders, duplicate reminders and many leftover tracks in the database. After looking at [this](https://github.com/dapr/dapr/issues/2705#issuecomment-767208221) post, we added a simple retry logic around the **unRegisterReminder** call and all our problems disappeared. We saw a number of 'eTag conflict' related exceptions during the unRegisterReminder call so the retry was making that work eventually. Only issue was the logs mentioned above.

**Comment by ItalyPaleAle** [comment]
@sujitdmello what version of Dapr were you using, and what state store?

we had some issues with etags etc and they should have been fixed between 1.10.6 and 1.11.0

**Comment by sujitdmello** [comment]
1.11.1 PostgreSQL

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ItalyPaleAle** [comment]
@sujitdmello were you seeing the missing reminders using 1.11.1 or an older version?

Can you provide a bit more details please? For example:

- Were the "etag errors" during creation?
   - Those are to be expected if you create a lot of reminders at the same time. The recommendation in that case is to simply retry the creation
- Were there reminders missing AFTER you got a successful response from the registerReminder methods?

**Comment by sujitdmello** [comment]
Yes there were eTag errors during creation but we got around that by having a retry loop for registerReminder which eventually succeeded. But there were still missing reminders until we added the retry loop for unregisterReminder as well.

**Comment by ItalyPaleAle** [comment]
That seems very odd. Is there a way we can repro this?

**Comment by seushermsft** [comment]
> That seems very odd. Is there a way we can repro this?

I work with Sujit and am going to spend some time next week getting the repro working locally on my machine.

With a quick look at the code, I'm wondering if it is unexpected. 

It looks like the code [here](https://github.com/dapr/dapr/blob/8b6059a01858f8558c13ab68483e2c04194cfce9/pkg/actors/actors.go#L937) loads the reminder from the `activeReminders` list, executes the reminder, and then tries to load it again from `activeReminders`.

In our Actor, we're calling `super.unregisterReminder(reminderName).block();`, which results in a call to the Actor's `doDeleteReminder`, which removes the reminder from the `activeReminders` collection [here](https://github.com/dapr/dapr/blob/8b6059a01858f8558c13ab68483e2c04194cfce9/pkg/actors/actors.go#L1666).

By the time the second lookup of the reminder happens in `activeReminders` [here](https://github.com/dapr/dapr/blob/8b6059a01858f8558c13ab68483e2c04194cfce9/pkg/actors/actors.go#L964), the reminder wouldn't be in the collection anymore.

I didn't do a deep dive into the code, so I may be missing something though.

**Comment by ItalyPaleAle** [comment]
@seushermsft thanks, I can take a look

**Comment by sujitdmello** [comment]
> /keep-alive

@ItalyPaleAle  is this something that should be reviewed in the current implementation or are there new design changes coming to Reminders that would address this eventually?
