### ISSUE TITLE
Dapr 1.12.3 appears to regress PubSub component load/connection in EShopOnDapr containers

### ISSUE THREAD

**Issue by paulyuk** [dapr/dapr#7362]
## In what area(s)?
/area runtime

## What version of Dapr?

> 1.12.3

## Expected Behavior

Context: Eshop is a rather complicated sample showing a distributed app.  It is implemented as a set of 23 containers, many of which are app containers or dependencies like Rabbitmq.  Each app also has a corresponding app-daprd container.  There is also a dapr-placement container and a blazor front end.

Expected:
Upon `docker-compose up` all containers pull, build and load into healthy running state.  

This following repro WORKS using 1.12.0 (and also 1.9.x)

1) clone this repo and dotnet8 branch: [paulyuk/eShopOnDapr at dotnet8 (github.com)](https://github.com/paulyuk/eShopOnDapr/tree/dotnet8)
2) docker-compose up  (you need only Docker, not Dapr on your host)
3a) check the health of your eshopondapr* containers in Docker Desktop, VSCode or docker ps .  There should be 23 healthy
3b) check health of containers on http://localhost:5107/ -- all should be healthy
4) test the web front end on http://localhost:5104/
 
*note daprd logs show successful component loads
`time="2024-01-11T01:47:53.15662668Z" level=info msg="Component loaded: eshopondapr-pubsub (pubsub.rabbitmq/v1)" app_id=webshoppingapigw instance=134475b1ae80 scope=dapr.runtime type=log ver=1.12.0`

All containers are running healthy, app runs end to end.  

## Actual Behavior

All Daprd containers fail and exit, and so do the apps depending on the sidecar.

Daprd logs show: 
`time="2024-01-11T01:34:07.948032131Z" level=error msg="Failed to init component eshopondapr-pubsub: [INIT_COMPONENT_FAILURE]: initialization error occurred for eshopondapr-pubsub (pubsub.rabbitmq/v1): dial tcp 172.18.0.10:5672: connect: connection refused" app_id=webshoppingagg instance=d106c6cb9f39 scope=dapr.runtime type=log ver=1.12.3`

## Steps to Reproduce the Problem

1) clone this repo and `dapr1-12-3issue` branch: [paulyuk/eShopOnDapr at dapr1-12-3issue (github.com)](https://github.com/paulyuk/eShopOnDapr/tree/dapr1-12-3issue) OR `git checkout dapr1-12-3issue`
** the only change is pulling docker images with `1.12.3` tag instead of `1.12.0`
2-4 steps are the same, except you'll see all dapdr containers fail

## Notes

I brainstormed with others and suspected a few things that we then invalidated:
- problems with Docker cache and network settings.  We would recycle Docker, system prune and so forth to be sure
- compose authoring problem putting placement container in wrong network.  This isn't the case given the conventions and names used.  also that would prevent 1.12.0 from working using the same compose file.
- if you make no other change than version numbers in docker compose file, the repro will consistently swap between working and broken states.  To me this rules out a number of external factors (although I suppose there could be an interaction I'm not detecting yet).

**Comment by yaron2** [comment]
Can you try and reproduce with 1.12.1 and 1.12.2? That would greatly help in identifying the potential root cause

**Comment by paulyuk** [comment]
@yaron2 I see the error repro starting in 1.12.1.  

Full results

1.9.4  pass
1.11.6 pass
1.12.0 pass
1.12.1 fail
1.12.2 fail
1.12.3 fail

**Comment by yaron2** [comment]
Here's the gist:

We're moving away from reconnection attempts in components to putting it in the runtime because in some components that would leave to issues where a component would report to the sidecar that it's healthy when in fact it is not. Most components error on init right away if the service (RabbitMQ, Redis etc.) isn't ready. In 1.12.1, we fixed a bug in the RabbitMQ component where it would *always* report to the sidecar that its healthy, even if it never becomes healthy. That behavior was wrong as it was both different from how ever components behave and also behaving differently from how we document the behavior to be (Dapr should panic and exit if the underlying service isn't ready at init time).

In the eShop app, all dependencies are not specified in depdends_on and do not have health checks to ensure that they're running before Dapr starts.

If you run the RabbitMQ container separately for example and then run the rest of the compose file, it will work as expected. Verified on my machine:

```
msg="Component loaded: eshopondapr-pubsub (pubsub.rabbitmq/v1)" app_id=webshoppingapigw instance=10495dc3e5b6 scope=dapr.runtime type=log ver=1.12.3```

**Comment by paulyuk** [comment]
Thanks for explaining. 

So far this still breaks an extremely common scenario (an app depending on a message queue broker or a db) in the inner loop.  My goal would be to still have a single compose file that runs this distributed app with all dependencies.

Do you think adding depends_on and a healthy condition is the right solution?  or are you suggesting multiple compose files (I really hope that's not the suggestion).

This is one of many user posts on the topic, with highly voted answers.  People want the "make sure X runs before Y" docker compose scenario to work :)

**Comment by yaron2** [comment]
> Do you think adding depends_on and a healthy condition is the right solution?

Yes, these features in Docker Compose are there to ensure that you have dependencies running and healthy before their downstream consumers are up. Running `docker-compose up rabbitq` separately and then another `docker-compose up` is also a viable way.

This worked for me: (would need to be added to all services using the pub/sub component, removed here for brevity)

```
rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 1s
      timeout: 2s
      retries: 10
```

With this in the override file:

```
rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
```

Then set the correct depends_on setting on the sidecar:

```
webshoppingagg-dapr:
    image: "ghcr.io/dapr/dapr:1.12.3"
    network_mode: "service:webshoppingagg"
    depends_on:
      webshoppingagg:
        condition: service_started
      rabbitmq:
        condition: service_healthy
```

This enables a healthcheck for RabbitMQ, and uses a Docker Compose setting that will only start the Dapr container once RabbitMQ is running with the help of the `condition: service_healthy` field.

**Comment by paulyuk** [comment]
Thank you!  I was misreading the suggestion.  I'll try this ASAP.  Once all good I can contribute this better approach back to EShop and also to our dapr.io doc on docker compose: https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/ (note I want to tweak this anyway because I feel it over complicates the docker networking by using a custom name for dapr placement container.. )
