### ISSUE TITLE
Intermittent Actor invocation timeout potentially linked to linkerd issues?

### ISSUE THREAD

**Issue by passuied** [dapr/dapr#8634]
## In what area(s)?

/area runtime

## What version of Dapr?

1.15.3

## Expected Behavior

The actor is invoked successfully

## Actual Behavior

Actor invocation or retrieval times out

## Steps to Reproduce the Problem

Hi, we've been running 1.15.3 in our dev and pre-prod environment for about 2 weeks and we've noticed some intermittent failures with actors. The error in daprd is a timeout error after 60s.
```
time="2025-03-28T03:23:20.158547687Z" level=info msg="HTTP API Called" app_id=note-predictions-api code=500 duration=60051 instance=note-predictions-api-sandbox-798457c48-tw8bf method="POST /v1.0/actors/PredictionSessionActor/session_a57871a0-4ead-4398-8314-c1653379a0ed/method/execute_final_prediction" scope=dapr.runtime.http-info size=233 type=log useragent=dapr-sdk-python/1.15.0 ver=1.15.3
```

Checking the logs, we see some linkerd errors (the pod also runs linkerd proxy) around the same time. These errors show up a lot more often throughout the day though and have appeared only since the upgrade:
```
Connection closed error=logical service 10.16.93.41:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.16.7.91:43846 server.addr=10.16.93.41:50006
```
```
Connection closed error=logical service 10.16.93.41:50005: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.16.7.91:43846 server.addr=10.16.93.41:50005
```

Restarting the pod fixes the issue...

The same service runs in Production on version 1.14.4 with scheduler disabled and does not exhibit the timeout issue or the linkerd connection timeouts.

Any ideas?

Is the linkerd 1s timeout too short? Does linkerd get in the way? We've had problem with linkerd in the past and ephemeral port ranges but that was at pod startup.
Is linkerd confused and no longer able to find the scheduler nodes after a while if the scheduler pods recycle? Or is the problem on the daprd sidecar?

## Release Note

RELEASE NOTE: **FIX** bug leading to intermittent actor timeouts

**Comment by yaron2** [comment]
If you can run the same setup without Linkerd that'd be best so we can rule if the issue is with Dapr or Linkerd.

**Comment by passuied** [comment]
I wish we could do this easily. I'll see what we can do

**Comment by passuied** [comment]
We're disabling linkerd on this service. We'll have to observe for a week to see if the issue has disappeared (the linkerd errors obviously will)

**Comment by passuied** [comment]
@yaron2 something we've noticed is that the IPs shown in those logs do NOT match the IPs of the scheduler server pods... Is it possible that daprd is somewhat caching old IPs even though the scheduler server pods recycled?

**Comment by passuied** [comment]
What we did to reproduce:
- recycle each scheduler server pod
- use service that leverages actors
- we see a huge spike of linkerd connection closed errors for older IPs. We couldn't replicate the actor timeout issue in dev though through this process....

**Comment by yaron2** [comment]
> [@yaron2](https://github.com/yaron2) something we've noticed is that the IPs shown in those logs do NOT match the IPs of the scheduler server pods... Is it possible that daprd is somewhat caching old IPs even though the scheduler server pods recycled?

@JoshVanL this is something we came across recently I think?

**Comment by passuied** [comment]
@yaron2 An update, what we're also doing in parallel, is implementing a resiliency policy for actors on that service to reduce the timeout and retries... Sounds like a sound idea?

**Comment by JoshVanL** [comment]
Yes, this looks like it is fixed in v1.15.4-rc.1
@passuied can you give that a try?

**Comment by passuied** [comment]
Amazing. Upgrading our dev server right now to test it out. Thanks @JoshVanL and @yaron2 !

**Comment by passuied** [comment]
Ok so I've done another round of testing after the upgrade:
- upon recycling all scheduler server nodes, I could see the connection time out errors from linkerd on port 50006. which I assume is expected while the nodes are restarting.
- however I am still seeing these 10 mins after the pods have restarted... This doesn't seem it should happen following the fix...
The daprd sidecar doesn't have any notable logs (though we don't have debug level enabled on the service).
During the test, I could make one of the actors time out, but I think it was because I cycled through the scheduler servers too quickly...  It did recover by itself, whereas the issue we experienced yesterday, only killing the pod would solve it...

**Comment by JoshVanL** [comment]
@passuied indeed, that still doesn't seem right- debug logs on both daprd and scheduler would definitely help here.

I also added [this](https://github.com/dapr/dapr/pull/8625) fix (not in v1.15.4-rc.1) which could be related (?). Only because I see a `500` code in your log output. Is there perhaps a cascade of retries going on- both internal to dapr, as well as linkerd?

Every daprd has a single, long lived gRPC connection to each of the scheduler servers on port 50006. As scheduler reorganizes itself on boot (or churn), these connections are closed and restarted. daprd is aggressive in retrying these connections. Could it be the case there are phantom retries happening in linkerd?

**Comment by passuied** [comment]
@JoshVanL Here is an interesting log from one of the pods which raise the  connection closed error...
I was focusing on a single instance of that service but expanding my search I found this one which seems to have a lot of daprd errors that are significant.

[All Messages Search Result (23).csv](https://github.com/user-attachments/files/19512710/All.Messages.Search.Result.23.csv)

**Comment by JoshVanL** [comment]
@passuied that panic definitely doesn't seem right! Will add a fix for this-

It is curious to me daprd is reconnecting to scheduler like this. Debug logs would really help to see why this is happening.

**Comment by passuied** [comment]
@JoshVanL another interesting logs below during another experimentation (recycling scheduler pods):
```
time="2025-03-28T21:51:41.865667352Z" level=info msg="Received updated scheduler hosts addresses: [10.19.3.136:50006 10.19.70.254:50006 10.19.156.182:50006]" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.865802915Z" level=info msg="Scheduler stream disconnected" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.cluster type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.865848435Z" level=info msg="Scheduler stream disconnected" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.cluster type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.865874806Z" level=info msg="Attempting to reconnect to schedulers" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.865903156Z" level=info msg="Attempting to connect to scheduler: dapr-scheduler-server-a.dapr-system.svc.cluster.local:443" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.878653128Z" level=info msg="Received scheduler hosts addresses: [10.19.3.136:50006 10.19.70.254:50006 10.19.156.182:50006]" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.87876967Z" level=info msg="Scheduler client initialized for address: 10.19.3.136:50006" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.clients type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.878971893Z" level=info msg="Scheduler client initialized for address: 10.19.70.254:50006" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.clients type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.879138676Z" level=info msg="Scheduler client initialized for address: 10.19.156.182:50006" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.clients type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.879152757Z" level=info msg="Scheduler clients initialized" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.clients type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.886778619Z" level=info msg="Scheduler stream connected" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.cluster type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.887602104Z" level=info msg="Scheduler stream connected" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.cluster type=log ver=1.15.4-rc.1
time="2025-03-28T21:51:41.952313226Z" level=info msg="Scheduler stream connected" app_id=note-predictions-api instance=note-predictions-api-dev-feature-rm-62321-7f987ff755-t49hq scope=dapr.runtime.scheduler.cluster type=log ver=1.15.4-rc.1
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:51:43.469303Z", "message": "request complete", "correlation_id": "0eea9a09-5df6-489b-a474-09a518bcf12c", "http_response_status": 200, "http_response_time_taken": 3, "scopes": [], "http_request_url": "http://10.19.2.138:8080/metrics", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/metrics", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:58000 - "GET /metrics HTTP/1.1" 200 OK
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:51:46.909965Z", "message": "request complete", "correlation_id": "2ddb8c39-6a1c-4dea-911c-f0063673b728", "http_response_status": 204, "http_response_time_taken": 3, "scopes": [], "http_request_url": "http://10.19.2.138:8080/health/live", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/health/live", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:58006 - "GET /health/live HTTP/1.1" 204 No Content
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:51:46.912769Z", "message": "request complete", "correlation_id": "cd437453-03b7-4469-ace0-012ef79849fc", "http_response_status": 204, "http_response_time_taken": 5, "scopes": [], "http_request_url": "http://10.19.2.138:8080/health/ready", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/health/ready", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:58010 - "GET /health/ready HTTP/1.1" 204 No Content
[  1531.256902s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=logical service 10.19.72.117:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.19.2.138:45088 server.addr=10.19.72.117:50006
[  1533.390472s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=logical service 10.19.9.175:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.19.2.138:53190 server.addr=10.19.9.175:50006
[  1535.698779s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=logical service 10.19.136.128:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.19.2.138:60632 server.addr=10.19.136.128:50006
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:51:56.910192Z", "message": "request complete", "correlation_id": "20f76b90-7b3a-42bb-aa93-440830eb222d", "http_response_status": 204, "http_response_time_taken": 3, "scopes": [], "http_request_url": "http://10.19.2.138:8080/health/ready", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/health/ready", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:34184 - "GET /health/ready HTTP/1.1" 204 No Content
[  1544.869551s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=logical service 10.19.136.128:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.19.2.138:48392 server.addr=10.19.136.128:50006
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:52:06.909944Z", "message": "request complete", "correlation_id": "b94c1d66-3e66-45ed-92bc-a68023b32e2c", "http_response_status": 204, "http_response_time_taken": 3, "scopes": [], "http_request_url": "http://10.19.2.138:8080/health/ready", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/health/ready", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:42648 - "GET /health/ready HTTP/1.1" 204 No Content
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:52:09.523815Z", "message": "request complete", "correlation_id": "fc87a080-d7d0-48db-9800-ead80700d1a8", "http_response_status": 200, "http_response_time_taken": 3, "scopes": [], "http_request_url": "http://10.19.2.138:8080/metrics", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/metrics", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:42664 - "GET /metrics HTTP/1.1" 200 OK
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:52:13.469037Z", "message": "request complete", "correlation_id": "b0d446b6-bce5-448a-8ded-88dbc50e7476", "http_response_status": 200, "http_response_time_taken": 3, "scopes": [], "http_request_url": "http://10.19.2.138:8080/metrics", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/metrics", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:34150 - "GET /metrics HTTP/1.1" 200 OK
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:52:16.909987Z", "message": "request complete", "correlation_id": "df67db65-0043-4d7f-837e-5c5aec3503af", "http_response_status": 204, "http_response_time_taken": 3, "scopes": [], "http_request_url": "http://10.19.2.138:8080/health/live", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/health/live", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:34160 - "GET /health/live HTTP/1.1" 204 No Content
{"logger": "instrumentation", "level": "info", "filename": "logging.py", "func_name": "log_middleware", "lineno": 58, "timestamp": "2025-03-28T21:52:16.912566Z", "message": "request complete", "correlation_id": "cd80d069-7262-41c0-bd60-c021bcf2fa03", "http_response_status": 204, "http_response_time_taken": 5, "scopes": [], "http_request_url": "http://10.19.2.138:8080/health/ready", "http_request_base_url": "http://10.19.2.138:8080/", "practice_ids": [], "http_request_path": "/health/ready", "http_request_method": "GET", "http_request_query": ""}
INFO:     10.19.2.138:34162 - "GET /health/ready HTTP/1.1" 204 No Content
[  1559.266516s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=logical service 10.19.72.117:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.19.2.138:53270 server.addr=10.19.72.117:50006
[  1567.421909s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=logical service 10.19.136.128:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.19.2.138:34890 server.addr=10.19.136.128:50006
```
Even though receiving the new set of addresses:
`Received updated scheduler hosts addresses: [10.19.3.136:50006 10.19.70.254:50006 10.19.156.182:50006]`
we still see subsequent errors to old addresses later
```
Connection closed error=logical service 10.19.72.117:50006: route default.endpoint: connect timed out after 1s error.sources=[route default.endpoint: connect timed out after 1s, connect timed out after 1s] client.addr=10.19.2.138:53270 server.addr=10.19.72.117:50006
```

**Comment by passuied** [comment]
An update that version 1.15.4-rc.3 that includes this the PR above resolves the connection timeout issue.
We were unable to reproduce easily the actor invocation locking issue so we're hoping this change and the other ones in version 1.15.4 will address it.
